apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: print-air-dev-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kudamhazo/prnt-air-yaml.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamepace=true
    automated:
      selfHeal: true
      prune: true